///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using OpenQA.Selenium;


using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SauceLabsTest0005
{
    public partial class Recording1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        /// 
        IWebDriver _driver;
        
        private void Init()
        {
        }
        
        public void TestValidate()
		{
		   // Create endpoint management factory
			var fac = new RemoteEndpointFactory();
			
			// Use existing endpoints
			var existing = fac.GetAll();
//			Report.Log(ReportLevel.Info, string.Format("Endpoints: {0}", existing.Count()));
			
			foreach (var e in existing)
			{
				Report.Log(ReportLevel.Info, string.Format("Name: {0}", e.DisplayName));
				e.ActivateConfig("Test Passed");
				
			}
			
			Report.Log(ReportLevel.Info, "Done");
			
			WebDocument wd = "/dom[]";
			
			wd.ExecuteScript("sauce:job-result=passed;");
			
			
		}

    }
}
