///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SauceLabsTest0005
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SauceLabsTest0005Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("dea8e64b-7b6a-433c-85b6-42f31359db88")]
    public partial class SauceLabsTest0005Repository : RepoGenBaseFolder
    {
        static SauceLabsTest0005Repository instance = new SauceLabsTest0005Repository();
        SauceLabsTest0005RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        SauceLabsTest0005RepositoryFolders.ExplorerAppFolder _explorer;
        SauceLabsTest0005RepositoryFolders.NewTabGoogleChromeAppFolder _newtabgooglechrome;
        SauceLabsTest0005RepositoryFolders.SwagLabsAppFolder _swaglabs;
        SauceLabsTest0005RepositoryFolders.SwagLabsGoogleChromeAppFolder _swaglabsgooglechrome;

        /// <summary>
        /// Gets the singleton class instance representing the SauceLabsTest0005Repository element repository.
        /// </summary>
        [RepositoryFolder("dea8e64b-7b6a-433c-85b6-42f31359db88")]
        public static SauceLabsTest0005Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SauceLabsTest0005Repository() 
            : base("SauceLabsTest0005Repository", "/", null, 0, false, "dea8e64b-7b6a-433c-85b6-42f31359db88", ".\\RepositoryImages\\SauceLabsTest0005Repositorydea8e64b.rximgres")
        {
            _applicationundertest = new SauceLabsTest0005RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _explorer = new SauceLabsTest0005RepositoryFolders.ExplorerAppFolder(this);
            _newtabgooglechrome = new SauceLabsTest0005RepositoryFolders.NewTabGoogleChromeAppFolder(this);
            _swaglabs = new SauceLabsTest0005RepositoryFolders.SwagLabsAppFolder(this);
            _swaglabsgooglechrome = new SauceLabsTest0005RepositoryFolders.SwagLabsGoogleChromeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("dea8e64b-7b6a-433c-85b6-42f31359db88")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("248cd8f6-42e5-4c43-983a-b3f6a44ab35e")]
        public virtual SauceLabsTest0005RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("dd9888f8-9a4c-4357-9e80-a07acfe5515f")]
        public virtual SauceLabsTest0005RepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The NewTabGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("5ff1e136-f330-4b1d-ab4e-c366d815d911")]
        public virtual SauceLabsTest0005RepositoryFolders.NewTabGoogleChromeAppFolder NewTabGoogleChrome
        {
            get { return _newtabgooglechrome; }
        }

        /// <summary>
        /// The SwagLabs folder.
        /// </summary>
        [RepositoryFolder("dc443146-b2cc-4b09-8462-ebf97386f5d4")]
        public virtual SauceLabsTest0005RepositoryFolders.SwagLabsAppFolder SwagLabs
        {
            get { return _swaglabs; }
        }

        /// <summary>
        /// The SwagLabsGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("a1fb4cac-5106-4050-b528-3d546b0799b7")]
        public virtual SauceLabsTest0005RepositoryFolders.SwagLabsGoogleChromeAppFolder SwagLabsGoogleChrome
        {
            get { return _swaglabsgooglechrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class SauceLabsTest0005RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("248cd8f6-42e5-4c43-983a-b3f6a44ab35e")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _submitInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.saucedemo.com']", parentFolder, 30000, null, false, "248cd8f6-42e5-4c43-983a-b3f6a44ab35e", "")
            {
                _submitInfo = new RepoItemInfo(this, "Submit", ".//div[#'login_button_container']/?/?/form[@action='https://www.saucedemo.com/']/input[@type='submit']", 30000, null, "600c16b3-6e67-469e-9f6d-db2a98e4d9bc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("248cd8f6-42e5-4c43-983a-b3f6a44ab35e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("248cd8f6-42e5-4c43-983a-b3f6a44ab35e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("600c16b3-6e67-469e-9f6d-db2a98e4d9bc")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("600c16b3-6e67-469e-9f6d-db2a98e4d9bc")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("dd9888f8-9a4c-4357-9e80-a07acfe5515f")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _eunjuchromeInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "dd9888f8-9a4c-4357-9e80-a07acfe5515f", "")
            {
                _eunjuchromeInfo = new RepoItemInfo(this, "EunjuChrome", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[@accessiblename='Eunju - Chrome']", 30000, null, "6027b206-6bac-41b8-b6f6-a854f52d1f0c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dd9888f8-9a4c-4357-9e80-a07acfe5515f")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dd9888f8-9a4c-4357-9e80-a07acfe5515f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EunjuChrome item.
            /// </summary>
            [RepositoryItem("6027b206-6bac-41b8-b6f6-a854f52d1f0c")]
            public virtual Ranorex.Button EunjuChrome
            {
                get
                {
                    return _eunjuchromeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EunjuChrome item info.
            /// </summary>
            [RepositoryItemInfo("6027b206-6bac-41b8-b6f6-a854f52d1f0c")]
            public virtual RepoItemInfo EunjuChromeInfo
            {
                get
                {
                    return _eunjuchromeInfo;
                }
            }
        }

        /// <summary>
        /// The NewTabGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("5ff1e136-f330-4b1d-ab4e-c366d815d911")]
        public partial class NewTabGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;
            RepoItemInfo _addressandsearchbarInfo;

            /// <summary>
            /// Creates a new NewTabGoogleChrome  folder.
            /// </summary>
            public NewTabGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NewTabGoogleChrome", "/form[@title='New Tab - Google Chrome']", parentFolder, 30000, null, true, "5ff1e136-f330-4b1d-ab4e-c366d815d911", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "container[@accessiblename>'New Tab - Google Chrome -']/container[@accessiblename='Google Chrome']//tabpage[@accessiblename='New Tab']/button[@accessiblename='Close']", 30000, null, "0fe00d96-30b6-4fc6-ab45-fa259893916f");
                _addressandsearchbarInfo = new RepoItemInfo(this, "AddressAndSearchBar", "container[@accessiblename>'Swag Labs - Google Chrome']/container[@accessiblename='Google Chrome']/container[2]/container[1]/container[2]/container[1]/text[@accessiblename='Address and search bar']", 30000, null, "40fd8da9-d684-40e8-91ee-cdd263f26285");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5ff1e136-f330-4b1d-ab4e-c366d815d911")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5ff1e136-f330-4b1d-ab4e-c366d815d911")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("0fe00d96-30b6-4fc6-ab45-fa259893916f")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("0fe00d96-30b6-4fc6-ab45-fa259893916f")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The AddressAndSearchBar item.
            /// </summary>
            [RepositoryItem("40fd8da9-d684-40e8-91ee-cdd263f26285")]
            public virtual Ranorex.Text AddressAndSearchBar
            {
                get
                {
                    return _addressandsearchbarInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AddressAndSearchBar item info.
            /// </summary>
            [RepositoryItemInfo("40fd8da9-d684-40e8-91ee-cdd263f26285")]
            public virtual RepoItemInfo AddressAndSearchBarInfo
            {
                get
                {
                    return _addressandsearchbarInfo;
                }
            }
        }

        /// <summary>
        /// The SwagLabsAppFolder folder.
        /// </summary>
        [RepositoryFolder("dc443146-b2cc-4b09-8462-ebf97386f5d4")]
        public partial class SwagLabsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _httpswwwsaucedemocomimgsaucebackInfo;

            /// <summary>
            /// Creates a new SwagLabs  folder.
            /// </summary>
            public SwagLabsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SwagLabs", "/dom[@domain='www.saucedemo.com']", parentFolder, 30000, null, false, "dc443146-b2cc-4b09-8462-ebf97386f5d4", "")
            {
                _usernameInfo = new RepoItemInfo(this, "UserName", ".//input[#'user-name']", 30000, null, "e3be4271-8c57-45e5-9a36-2b4c8e4c05ef");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", 30000, null, "cc69f48f-34fe-4a27-8d0c-cdd19e6802e4");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//input[@value='LOGIN']", 30000, null, "f90cdf0c-f2f4-44a3-986e-12604d545107");
                _httpswwwsaucedemocomimgsaucebackInfo = new RepoItemInfo(this, "HttpsWwwSaucedemoComImgSauceBack", ".//div[#'inventory_container']/?/?/div[@id='inventory_container']/div/div[1]//img[@src='https://www.saucedemo.com/img/sauce-backpack-1200x1500.jpg']", 30000, null, "e99119f7-1300-452a-bc11-f7f3bfaf8c83");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dc443146-b2cc-4b09-8462-ebf97386f5d4")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dc443146-b2cc-4b09-8462-ebf97386f5d4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserName item.
            /// </summary>
            [RepositoryItem("e3be4271-8c57-45e5-9a36-2b4c8e4c05ef")]
            public virtual Ranorex.InputTag UserName
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserName item info.
            /// </summary>
            [RepositoryItemInfo("e3be4271-8c57-45e5-9a36-2b4c8e4c05ef")]
            public virtual RepoItemInfo UserNameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("cc69f48f-34fe-4a27-8d0c-cdd19e6802e4")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("cc69f48f-34fe-4a27-8d0c-cdd19e6802e4")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("f90cdf0c-f2f4-44a3-986e-12604d545107")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("f90cdf0c-f2f4-44a3-986e-12604d545107")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The HttpsWwwSaucedemoComImgSauceBack item.
            /// </summary>
            [RepositoryItem("e99119f7-1300-452a-bc11-f7f3bfaf8c83")]
            public virtual Ranorex.ImgTag HttpsWwwSaucedemoComImgSauceBack
            {
                get
                {
                    return _httpswwwsaucedemocomimgsaucebackInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsWwwSaucedemoComImgSauceBack item info.
            /// </summary>
            [RepositoryItemInfo("e99119f7-1300-452a-bc11-f7f3bfaf8c83")]
            public virtual RepoItemInfo HttpsWwwSaucedemoComImgSauceBackInfo
            {
                get
                {
                    return _httpswwwsaucedemocomimgsaucebackInfo;
                }
            }
        }

        /// <summary>
        /// The SwagLabsGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("a1fb4cac-5106-4050-b528-3d546b0799b7")]
        public partial class SwagLabsGoogleChromeAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new SwagLabsGoogleChrome  folder.
            /// </summary>
            public SwagLabsGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SwagLabsGoogleChrome", "/form[@title='Swag Labs - Google Chrome']", parentFolder, 30000, null, true, "a1fb4cac-5106-4050-b528-3d546b0799b7", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a1fb4cac-5106-4050-b528-3d546b0799b7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a1fb4cac-5106-4050-b528-3d546b0799b7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
